apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: bb-grafana
  namespace: demo
spec:
  parameters:
    datasource: some-random-demo
  clientConfig:
    url: http://prometheus-grafana.monitoring.svc:80
  secret:
    name: grafana-key
